# ######
# Server
server:
  port: 8082
  tomcat:
    max-swallow-size: 300MB


# ###### ##########
# Spring Properties
spring:
  profiles:
    active: _REPLACE_         #   DEV or PROD   (logback-spring file contains 2 profiles)
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: _REPLACE_
    hibernate:
#      ddl-auto: create       # in case when schema recreation is necessary
      ddl-auto: update       # in case when it is not
    open-in-view: false
    properties:
      hibernate:
        dialect: _REPLACE_
        generate_statistics: _REPLACE_
        format_sql: _REPLACE_
        jdbc:
          time_zone: UTC
    show-sql: _REPLACE_
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      host: localhost
      port: 27017
      database: logs

  datasource:
    platform: _REPLACE_
    driver-class-name: _REPLACE_
    url: _REPLACE_
    username: _REPLACE_
    password: _REPLACE_
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  aop:
    auto: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .html


# ###### ##### #####
# Spring Query Utils
spring-hibernate-query-utils:
  n-plus-one-queries-detection:
    enabled: false


# #######
# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:**/mapper/*Mapper.xml


# #####
# Token
jwt:
  secret: _REPLACE_


# #####
# Email
email:
  admin_email_address: _REPLACE_
  sender_email_address: _REPLACE_
  sender_name: _REPLACE_
  password: _REPLACE_
  smtp_host: _REPLACE_
  smtp_port: _REPLACE_
