# ###### ##########
# Spring Properties
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        generate_statistics: true
#        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    # TODO: database credentials should be externalized later anyway!
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/squash_league_second
    url: jdbc:postgresql://localhost:5432/squashdb
    username: postgres
    password: squash123!@#


# #####
# Token
# TODO: secret should be externalized later anyway!
jwt:
  secret: QLTIh5c0pedaXdRzckPnlr1OCHuMcBmhHGzACijWJ0zlJ7Ua5LFkiRwX0e2TMIHo1tQLNHk6INSFc6JXY2g6letWJClMHYp2XO1f


# #####
# Email
# TODO: email credentials should be externalized later anyway!
email:
  sender_email_adress: dziadoliga@gmail.com
  sender_name: Dziadoliga Squash App
  password: Squash123!@#
  smtp_host: smtp.gmail.com
  smtp_port: 587


# #######
# Logging
#logging:
#  level:
#    org:
#      hibernate:
#        stat: debug


# May be useful later
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE