# ######
# Server
server:
  port: _REPLACE_


# ###### ##########
# Spring Properties
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: _REPLACE_
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: _REPLACE_
        generate_statistics: _REPLACE_
        format_sql: _REPLACE_
        jdbc:
          time_zone: UTC
    show-sql: _REPLACE_
  datasource:
    platform: _REPLACE_
    driver-class-name: _REPLACE_
    url: _REPLACE_
    username: _REPLACE_
    password: _REPLACE_


# #####
# Token
jwt:
  secret: _REPLACE_


# #####
# Email
email:
  sender_email_adress: _REPLACE_
  sender_name: _REPLACE_
  password: _REPLACE_
  smtp_host: _REPLACE_
  smtp_port: _REPLACE_
